language: go

go:
  - 1.7.1
  - tip

sudo: false

before_install:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/jteeuwen/go-bindata/...

script:
  - go generate -x
  - go build -o pugo.exe pugo.go 
  - ./pugo.exe build --theme="theme/default" --dest="default-dest"
  - ./pugo.exe build --theme="theme/pure" --dest="pure-dest"
  - ./pugo.exe build --theme="theme/uno" --dest="uno-test"
  - ./pugo.exe new post "this is new post"
  - ./pugo.exe new page "this is new page"
  - ./pugo.exe doc --no-server
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)