language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

sudo: false

script:
  - go get github.com/smartystreets/goconvey
  - go test -cover ./...
  - go build -o pugo.exe pugo.go && ./pugo.exe build --debug