[meta]
title = "PuGo"
subtitle = "Static Site Generator"
keyword = "pugo,golang,static,site,generator"
desc = "pugo is a simple static site generator"
domain = "pugo.io"
root = "http://pugo.io/"

[[nav]]
link = "/start/intro"
title = "Getting Started"
i18n = "start"
hover = "start"

[[nav]]
link = "/docs"
title = "Documentation"
i18n = "documentation"
hover = "docs"

[[nav]]
link = "https://github.com/go-xiaohei/pugo"
title = "Github"
i18n = "github"
icon = "fa fa-github"
blank = true

[[author]]
name = "pugo"
email = ""
url = "http://pugo.io"
bio = "the robot of pugo, who generates all default contents."

[comment]
disqus = "fuxiaohei"
duoshuo = ""

[analytics]
google = ""
baidu = ""

