[meta]
# site title, show in <title>
title = "PuGo"

# subtitle, words after title, in description
subtitle = "Static Site Generator"

# print in html <meta>
keyword = "pugo,golang,static,site,generator"

# print in html <meta>
desc = "PuGo is a Simple Static Site Generator"

# build links for feed, sitemap
domain = "localhost"

# root path for site# if empty, build as http://{domain}/
root = "http://localhost/blog/"

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "en"


[[nav]]
link = "/"
title = "Home"
i18n = "home"
# set nav to active status
hover = "index"
blank = false

[[nav]]
link = "/archive"
title = "Archive"
i18n = "archive"
hover = "archive"

[[nav]]
link = "/about"
title = "About"
i18n = "about"
hover = "about"

[[nav]]
link = "http://pugo.io"
title = "Source"
i18n = "source"
# browser open in new tab
blank = true

[[author]]
name = "pugo-robot"
email = ""
url = "http://pugo.io"
avatar = "@media/author.png"
bio = "the robot of pugo, who generates all default contents."

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = ""
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""
